CMD: "python mnist.py"

NUM_TRIALS: 10
HPARAMS: [
  {
   RUNX.TAG: 'sgd',
   lr: 0.01,
   momentum: [0.5, 0.25],
   logdir: LOGDIR,
  },
  {
   RUNX.TAG: 'adam',
   lr: {
    distribution: log_uniform,
    low: 0.0001,
    high: 0.1
   },
   momentum: [0.25, 0.12],
   logdir: LOGDIR,
  },
]

